# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QTMain.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_QMainWindow(object):
    def setupUi(self, QMainWindow):
        QMainWindow.setObjectName(_fromUtf8("QMainWindow"))
        QMainWindow.setWindowModality(QtCore.Qt.NonModal)
        QMainWindow.resize(962, 546)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        QMainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/ico/connections-512(1).png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        QMainWindow.setWindowIcon(icon)
        QMainWindow.setStyleSheet(_fromUtf8(""))
        self.centralwidget = QtGui.QWidget(QMainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.mdiArea = QtGui.QMdiArea(self.centralwidget)
        self.mdiArea.setStyleSheet(_fromUtf8(""))
        self.mdiArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.mdiArea.setFrameShadow(QtGui.QFrame.Plain)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.mdiArea.setBackground(brush)
        self.mdiArea.setActivationOrder(QtGui.QMdiArea.ActivationHistoryOrder)
        self.mdiArea.setViewMode(QtGui.QMdiArea.SubWindowView)
        self.mdiArea.setDocumentMode(False)
        self.mdiArea.setTabsMovable(False)
        self.mdiArea.setTabPosition(QtGui.QTabWidget.North)
        self.mdiArea.setObjectName(_fromUtf8("mdiArea"))
        self.gridLayout.addWidget(self.mdiArea, 0, 0, 1, 1)
        QMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(QMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 962, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.menubar.setFont(font)
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuMonitoreo = QtGui.QMenu(self.menubar)
        self.menuMonitoreo.setObjectName(_fromUtf8("menuMonitoreo"))
        self.menuClientes = QtGui.QMenu(self.menubar)
        self.menuClientes.setObjectName(_fromUtf8("menuClientes"))
        self.menuMapas = QtGui.QMenu(self.menubar)
        self.menuMapas.setObjectName(_fromUtf8("menuMapas"))
        self.menuVehiculos = QtGui.QMenu(self.menubar)
        self.menuVehiculos.setEnabled(False)
        self.menuVehiculos.setObjectName(_fromUtf8("menuVehiculos"))
        self.menuReportes = QtGui.QMenu(self.menubar)
        self.menuReportes.setObjectName(_fromUtf8("menuReportes"))
        self.menuMensajeria = QtGui.QMenu(self.menubar)
        self.menuMensajeria.setObjectName(_fromUtf8("menuMensajeria"))
        self.menuConfiguracio = QtGui.QMenu(self.menubar)
        self.menuConfiguracio.setObjectName(_fromUtf8("menuConfiguracio"))
        self.menuEquipos = QtGui.QMenu(self.menuConfiguracio)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/ico/Grupo_Codigo_Alarmas.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuEquipos.setIcon(icon1)
        self.menuEquipos.setObjectName(_fromUtf8("menuEquipos"))
        self.menuContacto365 = QtGui.QMenu(self.menubar)
        self.menuContacto365.setObjectName(_fromUtf8("menuContacto365"))
        QMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(QMainWindow)
        self.statusbar.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.statusbar.setStyleSheet(_fromUtf8("font: 10pt \"Calibri\";\n"
"background-color: #38648B;\n"
"color: rgb(255, 255, 255);"))
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        QMainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(QMainWindow)
        self.toolBar.setIconSize(QtCore.QSize(30, 30))
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        QMainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.toolBar_2 = QtGui.QToolBar(QMainWindow)
        self.toolBar_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.toolBar_2.setMovable(False)
        self.toolBar_2.setIconSize(QtCore.QSize(30, 30))
        self.toolBar_2.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolBar_2.setFloatable(False)
        self.toolBar_2.setObjectName(_fromUtf8("toolBar_2"))
        QMainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_2)
        self.dockWidget_ListaClientes = QtGui.QDockWidget(QMainWindow)
        self.dockWidget_ListaClientes.setMaximumSize(QtCore.QSize(524287, 524287))
        self.dockWidget_ListaClientes.setStyleSheet(_fromUtf8(""))
        self.dockWidget_ListaClientes.setFeatures(QtGui.QDockWidget.NoDockWidgetFeatures)
        self.dockWidget_ListaClientes.setAllowedAreas(QtCore.Qt.RightDockWidgetArea)
        self.dockWidget_ListaClientes.setObjectName(_fromUtf8("dockWidget_ListaClientes"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setStyleSheet(_fromUtf8(""))
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.gridLayout_2 = QtGui.QGridLayout(self.dockWidgetContents)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lineEdit_BuscarCliente = QtGui.QLineEdit(self.dockWidgetContents)
        self.lineEdit_BuscarCliente.setObjectName(_fromUtf8("lineEdit_BuscarCliente"))
        self.gridLayout_2.addWidget(self.lineEdit_BuscarCliente, 0, 1, 1, 1)
        self.label = QtGui.QLabel(self.dockWidgetContents)
        self.label.setMaximumSize(QtCore.QSize(20, 20))
        self.label.setText(_fromUtf8(""))
        self.label.setPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/ico/search (2).png")))
        self.label.setScaledContents(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 2, 1, 1)
        self.tableWidget_ListaClientes = QtGui.QTableWidget(self.dockWidgetContents)
        self.tableWidget_ListaClientes.setStyleSheet(_fromUtf8("font: 9pt \"Calibri\";"))
        self.tableWidget_ListaClientes.setObjectName(_fromUtf8("tableWidget_ListaClientes"))
        self.tableWidget_ListaClientes.setColumnCount(2)
        self.tableWidget_ListaClientes.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_ListaClientes.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget_ListaClientes.setHorizontalHeaderItem(1, item)
        self.tableWidget_ListaClientes.verticalHeader().setVisible(False)
        self.gridLayout_2.addWidget(self.tableWidget_ListaClientes, 1, 1, 1, 2)
        self.dockWidget_ListaClientes.setWidget(self.dockWidgetContents)
        QMainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget_ListaClientes)
        self.toolBar_3 = QtGui.QToolBar(QMainWindow)
        self.toolBar_3.setIconSize(QtCore.QSize(24, 24))
        self.toolBar_3.setObjectName(_fromUtf8("toolBar_3"))
        QMainWindow.addToolBar(QtCore.Qt.LeftToolBarArea, self.toolBar_3)
        self.toolBar_4 = QtGui.QToolBar(QMainWindow)
        self.toolBar_4.setObjectName(_fromUtf8("toolBar_4"))
        QMainWindow.addToolBar(QtCore.Qt.BottomToolBarArea, self.toolBar_4)
        self.actionLista_de_Clientes = QtGui.QAction(QMainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/ico/listaClientes3.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLista_de_Clientes.setIcon(icon2)
        self.actionLista_de_Clientes.setObjectName(_fromUtf8("actionLista_de_Clientes"))
        self.actionNuevo_Cliente = QtGui.QAction(QMainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/ico/Nuevo_Cliente3.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNuevo_Cliente.setIcon(icon3)
        self.actionNuevo_Cliente.setObjectName(_fromUtf8("actionNuevo_Cliente"))
        self.actionNuevo_Grupo = QtGui.QAction(QMainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/ico/Nuevo_grupo2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNuevo_Grupo.setIcon(icon4)
        self.actionNuevo_Grupo.setObjectName(_fromUtf8("actionNuevo_Grupo"))
        self.actionGrupos_de_Clientes = QtGui.QAction(QMainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/ico/GrupoClientes.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGrupos_de_Clientes.setIcon(icon5)
        self.actionGrupos_de_Clientes.setObjectName(_fromUtf8("actionGrupos_de_Clientes"))
        self.actionVer_Mapa = QtGui.QAction(QMainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/ico/map.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionVer_Mapa.setIcon(icon6)
        self.actionVer_Mapa.setObjectName(_fromUtf8("actionVer_Mapa"))
        self.actionZonas = QtGui.QAction(QMainWindow)
        self.actionZonas.setEnabled(False)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/ico/Maps.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZonas.setIcon(icon7)
        self.actionZonas.setObjectName(_fromUtf8("actionZonas"))
        self.actionActivaciones = QtGui.QAction(QMainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/ico/Activaciones_Report.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionActivaciones.setIcon(icon8)
        self.actionActivaciones.setObjectName(_fromUtf8("actionActivaciones"))
        self.actionGrupos_Alarmas = QtGui.QAction(QMainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/ico/Grupo_Señlales.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGrupos_Alarmas.setIcon(icon9)
        self.actionGrupos_Alarmas.setObjectName(_fromUtf8("actionGrupos_Alarmas"))
        self.actionCodigo_ALarmas = QtGui.QAction(QMainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/ico/Codigo_Alarmsd_report.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCodigo_ALarmas.setIcon(icon10)
        self.actionCodigo_ALarmas.setObjectName(_fromUtf8("actionCodigo_ALarmas"))
        self.actionEventos_no_definidos = QtGui.QAction(QMainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/ico/Eventos_no_defi.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEventos_no_definidos.setIcon(icon11)
        self.actionEventos_no_definidos.setObjectName(_fromUtf8("actionEventos_no_definidos"))
        self.actionSMS_Totales = QtGui.QAction(QMainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/ico/SMSTotales2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSMS_Totales.setIcon(icon12)
        self.actionSMS_Totales.setObjectName(_fromUtf8("actionSMS_Totales"))
        self.actionSMS_Entrada = QtGui.QAction(QMainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/ico/phone-update.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSMS_Entrada.setIcon(icon13)
        self.actionSMS_Entrada.setObjectName(_fromUtf8("actionSMS_Entrada"))
        self.actionSMS_Cliente = QtGui.QAction(QMainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/ico/Report_SMS_clie.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSMS_Cliente.setIcon(icon14)
        self.actionSMS_Cliente.setObjectName(_fromUtf8("actionSMS_Cliente"))
        self.actionEstatus_Panel = QtGui.QAction(QMainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/ico/object-stats.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEstatus_Panel.setIcon(icon15)
        self.actionEstatus_Panel.setObjectName(_fromUtf8("actionEstatus_Panel"))
        self.actionLinea_Receptor = QtGui.QAction(QMainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/ico/Linea_receptor.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLinea_Receptor.setIcon(icon16)
        self.actionLinea_Receptor.setObjectName(_fromUtf8("actionLinea_Receptor"))
        self.actionCliente = QtGui.QAction(QMainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/ico/Cliente_report.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCliente.setIcon(icon17)
        self.actionCliente.setObjectName(_fromUtf8("actionCliente"))
        self.actionFicha_Cliente = QtGui.QAction(QMainWindow)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/ico/ficha_cliente.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFicha_Cliente.setIcon(icon18)
        self.actionFicha_Cliente.setObjectName(_fromUtf8("actionFicha_Cliente"))
        self.actionClientes_sin_Coordenadas = QtGui.QAction(QMainWindow)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/ico/Cliente_sin_corrde.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClientes_sin_Coordenadas.setIcon(icon19)
        self.actionClientes_sin_Coordenadas.setObjectName(_fromUtf8("actionClientes_sin_Coordenadas"))
        self.actionClientes_sin_Imagen = QtGui.QAction(QMainWindow)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/ico/Cliente_sin_image.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClientes_sin_Imagen.setIcon(icon20)
        self.actionClientes_sin_Imagen.setObjectName(_fromUtf8("actionClientes_sin_Imagen"))
        self.actionZona_Clientes = QtGui.QAction(QMainWindow)
        self.actionZona_Clientes.setObjectName(_fromUtf8("actionZona_Clientes"))
        self.actionClientes_EMpresas = QtGui.QAction(QMainWindow)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/ico/Client_Empresa.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClientes_EMpresas.setIcon(icon21)
        self.actionClientes_EMpresas.setObjectName(_fromUtf8("actionClientes_EMpresas"))
        self.actionClientes_Ultima_Se_al = QtGui.QAction(QMainWindow)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/ico/Cliente_ultima_senal.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClientes_Ultima_Se_al.setIcon(icon22)
        self.actionClientes_Ultima_Se_al.setObjectName(_fromUtf8("actionClientes_Ultima_Se_al"))
        self.actionClientes_Ultima_A_C = QtGui.QAction(QMainWindow)
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/ico/Cliente_ap_cierre.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClientes_Ultima_A_C.setIcon(icon23)
        self.actionClientes_Ultima_A_C.setObjectName(_fromUtf8("actionClientes_Ultima_A_C"))
        self.actionLog_de_Usuarios = QtGui.QAction(QMainWindow)
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/ico/log_user.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLog_de_Usuarios.setIcon(icon24)
        self.actionLog_de_Usuarios.setObjectName(_fromUtf8("actionLog_de_Usuarios"))
        self.actionUsuarios = QtGui.QAction(QMainWindow)
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/ico/Usuarios_configuracion.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUsuarios.setIcon(icon25)
        self.actionUsuarios.setObjectName(_fromUtf8("actionUsuarios"))
        self.actionTipos_de_Usuarios = QtGui.QAction(QMainWindow)
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/ico/tipoUsuarios2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTipos_de_Usuarios.setIcon(icon26)
        self.actionTipos_de_Usuarios.setObjectName(_fromUtf8("actionTipos_de_Usuarios"))
        self.actionEmpresas = QtGui.QAction(QMainWindow)
        icon27 = QtGui.QIcon()
        icon27.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/ico/Empresas.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEmpresas.setIcon(icon27)
        self.actionEmpresas.setObjectName(_fromUtf8("actionEmpresas"))
        self.actionConfiguracion_Vehiculos = QtGui.QAction(QMainWindow)
        icon28 = QtGui.QIcon()
        icon28.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/ico/Config_Vehiculos.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConfiguracion_Vehiculos.setIcon(icon28)
        self.actionConfiguracion_Vehiculos.setObjectName(_fromUtf8("actionConfiguracion_Vehiculos"))
        self.actionParentesco = QtGui.QAction(QMainWindow)
        icon29 = QtGui.QIcon()
        icon29.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/ico/parentesco.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionParentesco.setIcon(icon29)
        self.actionParentesco.setObjectName(_fromUtf8("actionParentesco"))
        self.actionTipo_de_Cliente = QtGui.QAction(QMainWindow)
        icon30 = QtGui.QIcon()
        icon30.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/ico/company-employee.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTipo_de_Cliente.setIcon(icon30)
        self.actionTipo_de_Cliente.setObjectName(_fromUtf8("actionTipo_de_Cliente"))
        self.actionResoluciones = QtGui.QAction(QMainWindow)
        icon31 = QtGui.QIcon()
        icon31.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/ico/Resoluciones.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionResoluciones.setIcon(icon31)
        self.actionResoluciones.setObjectName(_fromUtf8("actionResoluciones"))
        self.actionTipo_de_Alarmas = QtGui.QAction(QMainWindow)
        icon32 = QtGui.QIcon()
        icon32.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/ico/panel_alarm.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTipo_de_Alarmas.setIcon(icon32)
        self.actionTipo_de_Alarmas.setObjectName(_fromUtf8("actionTipo_de_Alarmas"))
        self.actionEventos = QtGui.QAction(QMainWindow)
        icon33 = QtGui.QIcon()
        icon33.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/ico/Eventos.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEventos.setIcon(icon33)
        self.actionEventos.setObjectName(_fromUtf8("actionEventos"))
        self.actionCodigos_de_Alarma = QtGui.QAction(QMainWindow)
        icon34 = QtGui.QIcon()
        icon34.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/ico/Codigos_Alarmas.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCodigos_de_Alarma.setIcon(icon34)
        self.actionCodigos_de_Alarma.setObjectName(_fromUtf8("actionCodigos_de_Alarma"))
        self.actionGrupo_Codigos_de_Alarma = QtGui.QAction(QMainWindow)
        self.actionGrupo_Codigos_de_Alarma.setIcon(icon1)
        self.actionGrupo_Codigos_de_Alarma.setObjectName(_fromUtf8("actionGrupo_Codigos_de_Alarma"))
        self.actionDepartamentos = QtGui.QAction(QMainWindow)
        icon35 = QtGui.QIcon()
        icon35.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/ico/Departamentos3.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDepartamentos.setIcon(icon35)
        self.actionDepartamentos.setObjectName(_fromUtf8("actionDepartamentos"))
        self.actionMotivos_Soporte = QtGui.QAction(QMainWindow)
        icon36 = QtGui.QIcon()
        icon36.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/ico/Motivo_Soporte.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMotivos_Soporte.setIcon(icon36)
        self.actionMotivos_Soporte.setObjectName(_fromUtf8("actionMotivos_Soporte"))
        self.actionReceptores = QtGui.QAction(QMainWindow)
        icon37 = QtGui.QIcon()
        icon37.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/ico/Receptores.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionReceptores.setIcon(icon37)
        self.actionReceptores.setObjectName(_fromUtf8("actionReceptores"))
        self.actionDias_Feriados = QtGui.QAction(QMainWindow)
        self.actionDias_Feriados.setEnabled(False)
        icon38 = QtGui.QIcon()
        icon38.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/ico/Dias_Feriados.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDias_Feriados.setIcon(icon38)
        self.actionDias_Feriados.setObjectName(_fromUtf8("actionDias_Feriados"))
        self.actionSolicita_Soporte = QtGui.QAction(QMainWindow)
        icon39 = QtGui.QIcon()
        icon39.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/ico/help2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSolicita_Soporte.setIcon(icon39)
        self.actionSolicita_Soporte.setObjectName(_fromUtf8("actionSolicita_Soporte"))
        self.actionAcerca_de = QtGui.QAction(QMainWindow)
        icon40 = QtGui.QIcon()
        icon40.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/ico/warning-32.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAcerca_de.setIcon(icon40)
        self.actionAcerca_de.setObjectName(_fromUtf8("actionAcerca_de"))
        self.actionEnvio_de_SMS = QtGui.QAction(QMainWindow)
        self.actionEnvio_de_SMS.setEnabled(False)
        icon41 = QtGui.QIcon()
        icon41.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/ico/phone-favorite.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEnvio_de_SMS.setIcon(icon41)
        self.actionEnvio_de_SMS.setObjectName(_fromUtf8("actionEnvio_de_SMS"))
        self.actionEnvio_de_Correos = QtGui.QAction(QMainWindow)
        self.actionEnvio_de_Correos.setEnabled(False)
        icon42 = QtGui.QIcon()
        icon42.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/ico/mail_open-ok.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEnvio_de_Correos.setIcon(icon42)
        self.actionEnvio_de_Correos.setObjectName(_fromUtf8("actionEnvio_de_Correos"))
        self.actionIngresar_a_Monitoreo = QtGui.QAction(QMainWindow)
        icon43 = QtGui.QIcon()
        icon43.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/ico/Monitoreo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionIngresar_a_Monitoreo.setIcon(icon43)
        self.actionIngresar_a_Monitoreo.setIconVisibleInMenu(True)
        self.actionIngresar_a_Monitoreo.setObjectName(_fromUtf8("actionIngresar_a_Monitoreo"))
        self.actionPlanes = QtGui.QAction(QMainWindow)
        icon44 = QtGui.QIcon()
        icon44.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/ico/Eventos_Planes.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPlanes.setIcon(icon44)
        self.actionPlanes.setObjectName(_fromUtf8("actionPlanes"))
        self.actionModoVentana = QtGui.QAction(QMainWindow)
        icon45 = QtGui.QIcon()
        icon45.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/ico/ModernXP-69-Window-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionModoVentana.setIcon(icon45)
        self.actionModoVentana.setObjectName(_fromUtf8("actionModoVentana"))
        self.actionLateralBar = QtGui.QAction(QMainWindow)
        icon46 = QtGui.QIcon()
        icon46.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/ico/arrows_currency_exchange_direction_flat_icon-512.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLateralBar.setIcon(icon46)
        self.actionLateralBar.setObjectName(_fromUtf8("actionLateralBar"))
        self.actionMonitor_de_Alertas = QtGui.QAction(QMainWindow)
        icon47 = QtGui.QIcon()
        icon47.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/ico/Monitoreo_Alertas2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMonitor_de_Alertas.setIcon(icon47)
        self.actionMonitor_de_Alertas.setObjectName(_fromUtf8("actionMonitor_de_Alertas"))
        self.actionTipos = QtGui.QAction(QMainWindow)
        icon48 = QtGui.QIcon()
        icon48.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/ico/Tipo Equipos.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTipos.setIcon(icon48)
        self.actionTipos.setObjectName(_fromUtf8("actionTipos"))
        self.actionSub_Tipos_de_Equipos = QtGui.QAction(QMainWindow)
        icon49 = QtGui.QIcon()
        icon49.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/ico/Subtipo_Equipo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSub_Tipos_de_Equipos.setIcon(icon49)
        self.actionSub_Tipos_de_Equipos.setObjectName(_fromUtf8("actionSub_Tipos_de_Equipos"))
        self.actionMarcas = QtGui.QAction(QMainWindow)
        icon50 = QtGui.QIcon()
        icon50.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/ico/Marca_Equipos.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMarcas.setIcon(icon50)
        self.actionMarcas.setObjectName(_fromUtf8("actionMarcas"))
        self.actionModelos_de_Equipos = QtGui.QAction(QMainWindow)
        icon51 = QtGui.QIcon()
        icon51.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/ico/Modelo_Equipos.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionModelos_de_Equipos.setIcon(icon51)
        self.actionModelos_de_Equipos.setObjectName(_fromUtf8("actionModelos_de_Equipos"))
        self.actionLogin_Logout = QtGui.QAction(QMainWindow)
        icon52 = QtGui.QIcon()
        icon52.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/ico/group_2-logs.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLogin_Logout.setIcon(icon52)
        self.actionLogin_Logout.setObjectName(_fromUtf8("actionLogin_Logout"))
        self.menuMonitoreo.addAction(self.actionIngresar_a_Monitoreo)
        self.menuClientes.addAction(self.actionNuevo_Cliente)
        self.menuClientes.addAction(self.actionLista_de_Clientes)
        self.menuClientes.addSeparator()
        self.menuClientes.addAction(self.actionNuevo_Grupo)
        self.menuClientes.addAction(self.actionGrupos_de_Clientes)
        self.menuMapas.addAction(self.actionVer_Mapa)
        self.menuMapas.addAction(self.actionZonas)
        self.menuReportes.addAction(self.actionActivaciones)
        self.menuReportes.addAction(self.actionGrupos_Alarmas)
        self.menuReportes.addAction(self.actionCodigo_ALarmas)
        self.menuReportes.addAction(self.actionEventos_no_definidos)
        self.menuReportes.addSeparator()
        self.menuReportes.addAction(self.actionSMS_Totales)
        self.menuReportes.addAction(self.actionSMS_Entrada)
        self.menuReportes.addAction(self.actionSMS_Cliente)
        self.menuReportes.addSeparator()
        self.menuReportes.addAction(self.actionEstatus_Panel)
        self.menuReportes.addAction(self.actionLinea_Receptor)
        self.menuReportes.addAction(self.actionFicha_Cliente)
        self.menuReportes.addAction(self.actionClientes_sin_Coordenadas)
        self.menuReportes.addAction(self.actionClientes_sin_Imagen)
        self.menuReportes.addAction(self.actionClientes_EMpresas)
        self.menuReportes.addAction(self.actionClientes_Ultima_Se_al)
        self.menuReportes.addAction(self.actionClientes_Ultima_A_C)
        self.menuReportes.addAction(self.actionLog_de_Usuarios)
        self.menuMensajeria.addAction(self.actionMonitor_de_Alertas)
        self.menuMensajeria.addSeparator()
        self.menuMensajeria.addAction(self.actionEnvio_de_SMS)
        self.menuMensajeria.addAction(self.actionEnvio_de_Correos)
        self.menuMensajeria.addSeparator()
        self.menuMensajeria.addAction(self.actionPlanes)
        self.menuEquipos.addAction(self.actionTipos)
        self.menuEquipos.addAction(self.actionSub_Tipos_de_Equipos)
        self.menuEquipos.addAction(self.actionMarcas)
        self.menuEquipos.addAction(self.actionModelos_de_Equipos)
        self.menuConfiguracio.addAction(self.actionUsuarios)
        self.menuConfiguracio.addAction(self.actionTipos_de_Usuarios)
        self.menuConfiguracio.addSeparator()
        self.menuConfiguracio.addAction(self.actionEmpresas)
        self.menuConfiguracio.addSeparator()
        self.menuConfiguracio.addAction(self.actionConfiguracion_Vehiculos)
        self.menuConfiguracio.addAction(self.actionParentesco)
        self.menuConfiguracio.addAction(self.actionTipo_de_Cliente)
        self.menuConfiguracio.addAction(self.actionResoluciones)
        self.menuConfiguracio.addAction(self.actionEventos)
        self.menuConfiguracio.addAction(self.actionCodigos_de_Alarma)
        self.menuConfiguracio.addAction(self.actionGrupo_Codigos_de_Alarma)
        self.menuConfiguracio.addAction(self.actionDepartamentos)
        self.menuConfiguracio.addAction(self.actionMotivos_Soporte)
        self.menuConfiguracio.addAction(self.actionReceptores)
        self.menuConfiguracio.addAction(self.actionDias_Feriados)
        self.menuConfiguracio.addAction(self.menuEquipos.menuAction())
        self.menuContacto365.addAction(self.actionSolicita_Soporte)
        self.menuContacto365.addAction(self.actionAcerca_de)
        self.menubar.addAction(self.menuMonitoreo.menuAction())
        self.menubar.addAction(self.menuClientes.menuAction())
        self.menubar.addAction(self.menuMapas.menuAction())
        self.menubar.addAction(self.menuVehiculos.menuAction())
        self.menubar.addAction(self.menuReportes.menuAction())
        self.menubar.addAction(self.menuMensajeria.menuAction())
        self.menubar.addAction(self.menuConfiguracio.menuAction())
        self.menubar.addAction(self.menuContacto365.menuAction())
        self.toolBar.addAction(self.actionIngresar_a_Monitoreo)
        self.toolBar.addAction(self.actionMonitor_de_Alertas)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionLista_de_Clientes)
        self.toolBar.addAction(self.actionNuevo_Cliente)
        self.toolBar.addAction(self.actionGrupos_de_Clientes)
        self.toolBar.addAction(self.actionNuevo_Grupo)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionVer_Mapa)
        self.toolBar.addAction(self.actionZonas)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionEnvio_de_SMS)
        self.toolBar.addAction(self.actionEnvio_de_Correos)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionSolicita_Soporte)
        self.toolBar.addAction(self.actionModoVentana)
        self.toolBar_2.addAction(self.actionLateralBar)
        self.toolBar_2.addAction(self.actionLogin_Logout)
        self.toolBar_3.addAction(self.actionUsuarios)
        self.toolBar_3.addAction(self.actionTipos_de_Usuarios)
        self.toolBar_3.addAction(self.actionEmpresas)
        self.toolBar_3.addAction(self.actionConfiguracion_Vehiculos)
        self.toolBar_3.addAction(self.actionParentesco)
        self.toolBar_3.addAction(self.actionTipo_de_Cliente)
        self.toolBar_3.addAction(self.actionResoluciones)
        self.toolBar_3.addAction(self.actionEventos)
        self.toolBar_3.addAction(self.actionCodigos_de_Alarma)
        self.toolBar_3.addAction(self.actionGrupo_Codigos_de_Alarma)
        self.toolBar_3.addAction(self.actionDepartamentos)
        self.toolBar_3.addAction(self.actionMotivos_Soporte)
        self.toolBar_3.addAction(self.actionReceptores)
        self.toolBar_3.addAction(self.actionDias_Feriados)
        self.toolBar_4.addAction(self.actionActivaciones)
        self.toolBar_4.addAction(self.actionGrupos_Alarmas)
        self.toolBar_4.addAction(self.actionCodigo_ALarmas)
        self.toolBar_4.addAction(self.actionSMS_Totales)
        self.toolBar_4.addAction(self.actionSMS_Entrada)
        self.toolBar_4.addAction(self.actionEstatus_Panel)

        self.retranslateUi(QMainWindow)
        QtCore.QMetaObject.connectSlotsByName(QMainWindow)

    def retranslateUi(self, QMainWindow):
        QMainWindow.setWindowTitle(_translate("QMainWindow", "365Connect", None))
        self.menuMonitoreo.setTitle(_translate("QMainWindow", "Monitoreo", None))
        self.menuClientes.setTitle(_translate("QMainWindow", "Clientes", None))
        self.menuMapas.setTitle(_translate("QMainWindow", "Mapas", None))
        self.menuVehiculos.setTitle(_translate("QMainWindow", "Vehiculos", None))
        self.menuReportes.setTitle(_translate("QMainWindow", "Reportes", None))
        self.menuMensajeria.setTitle(_translate("QMainWindow", "SMS/Mail", None))
        self.menuConfiguracio.setTitle(_translate("QMainWindow", "Configuracion", None))
        self.menuEquipos.setTitle(_translate("QMainWindow", "Equipos", None))
        self.menuContacto365.setTitle(_translate("QMainWindow", "Contacto365", None))
        self.toolBar.setWindowTitle(_translate("QMainWindow", "toolBar", None))
        self.toolBar_2.setWindowTitle(_translate("QMainWindow", "toolBar_2", None))
        self.dockWidget_ListaClientes.setWindowTitle(_translate("QMainWindow", "Lista de Clientes.", None))
        self.lineEdit_BuscarCliente.setPlaceholderText(_translate("QMainWindow", "Buscar Cliente", None))
        item = self.tableWidget_ListaClientes.horizontalHeaderItem(0)
        item.setText(_translate("QMainWindow", "ID", None))
        item = self.tableWidget_ListaClientes.horizontalHeaderItem(1)
        item.setText(_translate("QMainWindow", "Nombre", None))
        self.toolBar_3.setWindowTitle(_translate("QMainWindow", "toolBar_3", None))
        self.toolBar_4.setWindowTitle(_translate("QMainWindow", "toolBar_4", None))
        self.actionLista_de_Clientes.setText(_translate("QMainWindow", "Lista de Clientes", None))
        self.actionLista_de_Clientes.setStatusTip(_translate("QMainWindow", "Listar Todos los Clientes del Sistema", None))
        self.actionLista_de_Clientes.setShortcut(_translate("QMainWindow", "Ctrl+C", None))
        self.actionNuevo_Cliente.setText(_translate("QMainWindow", "Nuevo Cliente", None))
        self.actionNuevo_Cliente.setStatusTip(_translate("QMainWindow", "Agregar un Cliente", None))
        self.actionNuevo_Cliente.setShortcut(_translate("QMainWindow", "Shift+C", None))
        self.actionNuevo_Grupo.setText(_translate("QMainWindow", "Nuevo Grupo", None))
        self.actionNuevo_Grupo.setStatusTip(_translate("QMainWindow", "Crear Nuevo Grupo de Clientes", None))
        self.actionNuevo_Grupo.setShortcut(_translate("QMainWindow", "Shift+G", None))
        self.actionGrupos_de_Clientes.setText(_translate("QMainWindow", "Grupos de Clientes", None))
        self.actionGrupos_de_Clientes.setStatusTip(_translate("QMainWindow", "Listar Grupos de Clientes del Sistema", None))
        self.actionGrupos_de_Clientes.setShortcut(_translate("QMainWindow", "Ctrl+G", None))
        self.actionVer_Mapa.setText(_translate("QMainWindow", "Ver Mapa", None))
        self.actionVer_Mapa.setStatusTip(_translate("QMainWindow", "Ver Mapa de Ubicacion de Clientes", None))
        self.actionVer_Mapa.setShortcut(_translate("QMainWindow", "Shift+M", None))
        self.actionZonas.setText(_translate("QMainWindow", "Zonas", None))
        self.actionZonas.setStatusTip(_translate("QMainWindow", "Gestionar Zonas del Mapa", None))
        self.actionZonas.setShortcut(_translate("QMainWindow", "Ctrl+Z", None))
        self.actionActivaciones.setText(_translate("QMainWindow", "Activaciones", None))
        self.actionGrupos_Alarmas.setText(_translate("QMainWindow", "Grupos Alarmas", None))
        self.actionCodigo_ALarmas.setText(_translate("QMainWindow", "Codigo Alarmas", None))
        self.actionEventos_no_definidos.setText(_translate("QMainWindow", "Eventos No Definidos", None))
        self.actionSMS_Totales.setText(_translate("QMainWindow", "SMS Totales", None))
        self.actionSMS_Entrada.setText(_translate("QMainWindow", "SMS Entrada", None))
        self.actionSMS_Cliente.setText(_translate("QMainWindow", "SMS Cliente", None))
        self.actionEstatus_Panel.setText(_translate("QMainWindow", "Estatus Panel", None))
        self.actionLinea_Receptor.setText(_translate("QMainWindow", "Linea Receptor", None))
        self.actionCliente.setText(_translate("QMainWindow", "Cliente", None))
        self.actionFicha_Cliente.setText(_translate("QMainWindow", "Ficha Cliente", None))
        self.actionClientes_sin_Coordenadas.setText(_translate("QMainWindow", "Clientes sin Coordenadas", None))
        self.actionClientes_sin_Imagen.setText(_translate("QMainWindow", "Clientes sin Imagen", None))
        self.actionZona_Clientes.setText(_translate("QMainWindow", "Zona Clientes", None))
        self.actionClientes_EMpresas.setText(_translate("QMainWindow", "Clientes Empresas", None))
        self.actionClientes_Ultima_Se_al.setText(_translate("QMainWindow", "Clientes Ultima Señal", None))
        self.actionClientes_Ultima_A_C.setText(_translate("QMainWindow", "Clientes Ultima A/C", None))
        self.actionLog_de_Usuarios.setText(_translate("QMainWindow", "Log de Usuarios", None))
        self.actionUsuarios.setText(_translate("QMainWindow", "Usuarios", None))
        self.actionTipos_de_Usuarios.setText(_translate("QMainWindow", "Tipos de Usuarios", None))
        self.actionEmpresas.setText(_translate("QMainWindow", "Empresas", None))
        self.actionConfiguracion_Vehiculos.setText(_translate("QMainWindow", "Configuracion Vehiculos", None))
        self.actionParentesco.setText(_translate("QMainWindow", "Parentesco", None))
        self.actionTipo_de_Cliente.setText(_translate("QMainWindow", "Tipo de Cliente", None))
        self.actionResoluciones.setText(_translate("QMainWindow", "Resoluciones", None))
        self.actionTipo_de_Alarmas.setText(_translate("QMainWindow", "Tipo de Alarmas", None))
        self.actionEventos.setText(_translate("QMainWindow", "Eventos", None))
        self.actionCodigos_de_Alarma.setText(_translate("QMainWindow", "Codigos de Alarma", None))
        self.actionGrupo_Codigos_de_Alarma.setText(_translate("QMainWindow", "Grupo Codigos de Alarma", None))
        self.actionDepartamentos.setText(_translate("QMainWindow", "Departamentos", None))
        self.actionMotivos_Soporte.setText(_translate("QMainWindow", "Motivos Soporte", None))
        self.actionReceptores.setText(_translate("QMainWindow", "Receptores", None))
        self.actionDias_Feriados.setText(_translate("QMainWindow", "Dias Feriados", None))
        self.actionSolicita_Soporte.setText(_translate("QMainWindow", "Solicita Soporte", None))
        self.actionSolicita_Soporte.setStatusTip(_translate("QMainWindow", "Obten Soporte Directo con 365", None))
        self.actionSolicita_Soporte.setShortcut(_translate("QMainWindow", "Ctrl+H", None))
        self.actionAcerca_de.setText(_translate("QMainWindow", "Acerca de", None))
        self.actionAcerca_de.setStatusTip(_translate("QMainWindow", "Acerca de 365 Monitoring Software", None))
        self.actionEnvio_de_SMS.setText(_translate("QMainWindow", "Envio de SMS", None))
        self.actionEnvio_de_SMS.setStatusTip(_translate("QMainWindow", "Enviar Mensajes de Texto", None))
        self.actionEnvio_de_SMS.setShortcut(_translate("QMainWindow", "Ctrl+E", None))
        self.actionEnvio_de_Correos.setText(_translate("QMainWindow", "Envio de Correos", None))
        self.actionEnvio_de_Correos.setStatusTip(_translate("QMainWindow", "Enviar Correos Electronicos", None))
        self.actionEnvio_de_Correos.setShortcut(_translate("QMainWindow", "Ctrl+S", None))
        self.actionIngresar_a_Monitoreo.setText(_translate("QMainWindow", "Ingresar a Monitoreo", None))
        self.actionIngresar_a_Monitoreo.setStatusTip(_translate("QMainWindow", "Accede al Area de Monitoreo", None))
        self.actionIngresar_a_Monitoreo.setShortcut(_translate("QMainWindow", "Ctrl+M", None))
        self.actionPlanes.setText(_translate("QMainWindow", "Planes", None))
        self.actionModoVentana.setText(_translate("QMainWindow", "Modo de Ventana", None))
        self.actionModoVentana.setToolTip(_translate("QMainWindow", "Cambiar Modo Ventana", None))
        self.actionLateralBar.setText(_translate("QMainWindow", "LateralBar", None))
        self.actionMonitor_de_Alertas.setText(_translate("QMainWindow", "Monitor de Alertas", None))
        self.actionTipos.setText(_translate("QMainWindow", "Tipos de Equipos", None))
        self.actionSub_Tipos_de_Equipos.setText(_translate("QMainWindow", "Sub Tipos de Equipos", None))
        self.actionMarcas.setText(_translate("QMainWindow", "Marcas de Equipos", None))
        self.actionModelos_de_Equipos.setText(_translate("QMainWindow", "Modelos de Equipos", None))
        self.actionLogin_Logout.setText(_translate("QMainWindow", "Login/Logout", None))
        self.actionLogin_Logout.setToolTip(_translate("QMainWindow", "Login/Logout", None))

import recursos_rc
