# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QTMain.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_QMainWindow(object):
    def setupUi(self, QMainWindow):
        QMainWindow.setObjectName(_fromUtf8("QMainWindow"))
        QMainWindow.setWindowModality(QtCore.Qt.NonModal)
        QMainWindow.resize(775, 600)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        QMainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/ico/connections-512(1).png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        QMainWindow.setWindowIcon(icon)
        QMainWindow.setStyleSheet(_fromUtf8(""))
        self.centralwidget = QtGui.QWidget(QMainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.mdiArea = QtGui.QMdiArea(self.centralwidget)
        self.mdiArea.setStyleSheet(_fromUtf8(""))
        self.mdiArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.mdiArea.setFrameShadow(QtGui.QFrame.Plain)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.mdiArea.setBackground(brush)
        self.mdiArea.setActivationOrder(QtGui.QMdiArea.CreationOrder)
        self.mdiArea.setObjectName(_fromUtf8("mdiArea"))
        self.gridLayout.addWidget(self.mdiArea, 0, 0, 1, 1)
        QMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(QMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 775, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.menubar.setFont(font)
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuMonitoreo = QtGui.QMenu(self.menubar)
        self.menuMonitoreo.setObjectName(_fromUtf8("menuMonitoreo"))
        self.menuClientes = QtGui.QMenu(self.menubar)
        self.menuClientes.setObjectName(_fromUtf8("menuClientes"))
        self.menuMapas = QtGui.QMenu(self.menubar)
        self.menuMapas.setObjectName(_fromUtf8("menuMapas"))
        self.menuVehiculos = QtGui.QMenu(self.menubar)
        self.menuVehiculos.setObjectName(_fromUtf8("menuVehiculos"))
        self.menuReportes = QtGui.QMenu(self.menubar)
        self.menuReportes.setObjectName(_fromUtf8("menuReportes"))
        self.menuMensajeria = QtGui.QMenu(self.menubar)
        self.menuMensajeria.setObjectName(_fromUtf8("menuMensajeria"))
        self.menuConfiguracio = QtGui.QMenu(self.menubar)
        self.menuConfiguracio.setObjectName(_fromUtf8("menuConfiguracio"))
        self.menuContacto365 = QtGui.QMenu(self.menubar)
        self.menuContacto365.setObjectName(_fromUtf8("menuContacto365"))
        QMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(QMainWindow)
        self.statusbar.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.statusbar.setStyleSheet(_fromUtf8("font: 10pt \"Calibri\";\n"
"background-color: #38648B;\n"
"color: rgb(255, 255, 255);"))
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        QMainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(QMainWindow)
        self.toolBar.setIconSize(QtCore.QSize(35, 35))
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        QMainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionLista_de_Clientes = QtGui.QAction(QMainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/ico/Document 2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLista_de_Clientes.setIcon(icon1)
        self.actionLista_de_Clientes.setObjectName(_fromUtf8("actionLista_de_Clientes"))
        self.actionNuevo_Cliente = QtGui.QAction(QMainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/ico/CLIENTE.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNuevo_Cliente.setIcon(icon2)
        self.actionNuevo_Cliente.setObjectName(_fromUtf8("actionNuevo_Cliente"))
        self.actionNuevo_Grupo = QtGui.QAction(QMainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/ico/Box Add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNuevo_Grupo.setIcon(icon3)
        self.actionNuevo_Grupo.setObjectName(_fromUtf8("actionNuevo_Grupo"))
        self.actionGrupos_de_Clientes = QtGui.QAction(QMainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/ico/Box.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGrupos_de_Clientes.setIcon(icon4)
        self.actionGrupos_de_Clientes.setObjectName(_fromUtf8("actionGrupos_de_Clientes"))
        self.actionVer_Mapa = QtGui.QAction(QMainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/ico/map.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionVer_Mapa.setIcon(icon5)
        self.actionVer_Mapa.setObjectName(_fromUtf8("actionVer_Mapa"))
        self.actionZonas = QtGui.QAction(QMainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/ico/Maps.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZonas.setIcon(icon6)
        self.actionZonas.setObjectName(_fromUtf8("actionZonas"))
        self.actionActivaciones = QtGui.QAction(QMainWindow)
        self.actionActivaciones.setObjectName(_fromUtf8("actionActivaciones"))
        self.actionGrupos_Alarmas = QtGui.QAction(QMainWindow)
        self.actionGrupos_Alarmas.setObjectName(_fromUtf8("actionGrupos_Alarmas"))
        self.actionCodigo_ALarmas = QtGui.QAction(QMainWindow)
        self.actionCodigo_ALarmas.setObjectName(_fromUtf8("actionCodigo_ALarmas"))
        self.actionEventos_no_definidos = QtGui.QAction(QMainWindow)
        self.actionEventos_no_definidos.setObjectName(_fromUtf8("actionEventos_no_definidos"))
        self.actionSMS_Totales = QtGui.QAction(QMainWindow)
        self.actionSMS_Totales.setObjectName(_fromUtf8("actionSMS_Totales"))
        self.actionSMS_Entrada = QtGui.QAction(QMainWindow)
        self.actionSMS_Entrada.setObjectName(_fromUtf8("actionSMS_Entrada"))
        self.actionSMS_Cliente = QtGui.QAction(QMainWindow)
        self.actionSMS_Cliente.setObjectName(_fromUtf8("actionSMS_Cliente"))
        self.actionEstatus_Panel = QtGui.QAction(QMainWindow)
        self.actionEstatus_Panel.setObjectName(_fromUtf8("actionEstatus_Panel"))
        self.actionLinea_Receptor = QtGui.QAction(QMainWindow)
        self.actionLinea_Receptor.setObjectName(_fromUtf8("actionLinea_Receptor"))
        self.actionCliente = QtGui.QAction(QMainWindow)
        self.actionCliente.setObjectName(_fromUtf8("actionCliente"))
        self.actionFicha_Cliente = QtGui.QAction(QMainWindow)
        self.actionFicha_Cliente.setObjectName(_fromUtf8("actionFicha_Cliente"))
        self.actionClientes_sin_Coordenadas = QtGui.QAction(QMainWindow)
        self.actionClientes_sin_Coordenadas.setObjectName(_fromUtf8("actionClientes_sin_Coordenadas"))
        self.actionClientes_sin_Imagen = QtGui.QAction(QMainWindow)
        self.actionClientes_sin_Imagen.setObjectName(_fromUtf8("actionClientes_sin_Imagen"))
        self.actionZona_Clientes = QtGui.QAction(QMainWindow)
        self.actionZona_Clientes.setObjectName(_fromUtf8("actionZona_Clientes"))
        self.actionClientes_EMpresas = QtGui.QAction(QMainWindow)
        self.actionClientes_EMpresas.setObjectName(_fromUtf8("actionClientes_EMpresas"))
        self.actionClientes_Ultima_Se_al = QtGui.QAction(QMainWindow)
        self.actionClientes_Ultima_Se_al.setObjectName(_fromUtf8("actionClientes_Ultima_Se_al"))
        self.actionClientes_Ultima_A_C = QtGui.QAction(QMainWindow)
        self.actionClientes_Ultima_A_C.setObjectName(_fromUtf8("actionClientes_Ultima_A_C"))
        self.actionLog_de_Usuarios = QtGui.QAction(QMainWindow)
        self.actionLog_de_Usuarios.setObjectName(_fromUtf8("actionLog_de_Usuarios"))
        self.actionUsuarios = QtGui.QAction(QMainWindow)
        self.actionUsuarios.setObjectName(_fromUtf8("actionUsuarios"))
        self.actionTipos_de_Usuarios = QtGui.QAction(QMainWindow)
        self.actionTipos_de_Usuarios.setObjectName(_fromUtf8("actionTipos_de_Usuarios"))
        self.actionEmpresas = QtGui.QAction(QMainWindow)
        self.actionEmpresas.setObjectName(_fromUtf8("actionEmpresas"))
        self.actionConfiguracion_Vehiculos = QtGui.QAction(QMainWindow)
        self.actionConfiguracion_Vehiculos.setObjectName(_fromUtf8("actionConfiguracion_Vehiculos"))
        self.actionParentesco = QtGui.QAction(QMainWindow)
        self.actionParentesco.setObjectName(_fromUtf8("actionParentesco"))
        self.actionTipo_de_Cliente = QtGui.QAction(QMainWindow)
        self.actionTipo_de_Cliente.setObjectName(_fromUtf8("actionTipo_de_Cliente"))
        self.actionResoluciones = QtGui.QAction(QMainWindow)
        self.actionResoluciones.setObjectName(_fromUtf8("actionResoluciones"))
        self.actionTipo_de_Alarmas = QtGui.QAction(QMainWindow)
        self.actionTipo_de_Alarmas.setObjectName(_fromUtf8("actionTipo_de_Alarmas"))
        self.actionEventos = QtGui.QAction(QMainWindow)
        self.actionEventos.setObjectName(_fromUtf8("actionEventos"))
        self.actionCodigos_de_Alarma = QtGui.QAction(QMainWindow)
        self.actionCodigos_de_Alarma.setObjectName(_fromUtf8("actionCodigos_de_Alarma"))
        self.actionGrupo_Codigos_de_Alarma = QtGui.QAction(QMainWindow)
        self.actionGrupo_Codigos_de_Alarma.setObjectName(_fromUtf8("actionGrupo_Codigos_de_Alarma"))
        self.actionDepartamentos = QtGui.QAction(QMainWindow)
        self.actionDepartamentos.setObjectName(_fromUtf8("actionDepartamentos"))
        self.actionMotivos_Soporte = QtGui.QAction(QMainWindow)
        self.actionMotivos_Soporte.setObjectName(_fromUtf8("actionMotivos_Soporte"))
        self.actionReceptores = QtGui.QAction(QMainWindow)
        self.actionReceptores.setObjectName(_fromUtf8("actionReceptores"))
        self.actionDias_Feriados = QtGui.QAction(QMainWindow)
        self.actionDias_Feriados.setObjectName(_fromUtf8("actionDias_Feriados"))
        self.actionSolicita_Soporte = QtGui.QAction(QMainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/ico/help.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSolicita_Soporte.setIcon(icon7)
        self.actionSolicita_Soporte.setObjectName(_fromUtf8("actionSolicita_Soporte"))
        self.actionAcerca_de = QtGui.QAction(QMainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/ico/warning-32.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAcerca_de.setIcon(icon8)
        self.actionAcerca_de.setObjectName(_fromUtf8("actionAcerca_de"))
        self.actionEnvio_de_SMS = QtGui.QAction(QMainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/ico/bubble.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEnvio_de_SMS.setIcon(icon9)
        self.actionEnvio_de_SMS.setObjectName(_fromUtf8("actionEnvio_de_SMS"))
        self.actionEnvio_de_Correos = QtGui.QAction(QMainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/ico/Mail Add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEnvio_de_Correos.setIcon(icon10)
        self.actionEnvio_de_Correos.setObjectName(_fromUtf8("actionEnvio_de_Correos"))
        self.actionIngresar_a_Monitoreo = QtGui.QAction(QMainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/ico/monitor.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionIngresar_a_Monitoreo.setIcon(icon11)
        self.actionIngresar_a_Monitoreo.setIconVisibleInMenu(True)
        self.actionIngresar_a_Monitoreo.setObjectName(_fromUtf8("actionIngresar_a_Monitoreo"))
        self.menuMonitoreo.addAction(self.actionIngresar_a_Monitoreo)
        self.menuClientes.addAction(self.actionNuevo_Cliente)
        self.menuClientes.addAction(self.actionLista_de_Clientes)
        self.menuClientes.addSeparator()
        self.menuClientes.addAction(self.actionNuevo_Grupo)
        self.menuClientes.addAction(self.actionGrupos_de_Clientes)
        self.menuMapas.addAction(self.actionVer_Mapa)
        self.menuMapas.addAction(self.actionZonas)
        self.menuReportes.addAction(self.actionActivaciones)
        self.menuReportes.addAction(self.actionGrupos_Alarmas)
        self.menuReportes.addAction(self.actionCodigo_ALarmas)
        self.menuReportes.addAction(self.actionEventos_no_definidos)
        self.menuReportes.addSeparator()
        self.menuReportes.addAction(self.actionSMS_Totales)
        self.menuReportes.addAction(self.actionSMS_Entrada)
        self.menuReportes.addAction(self.actionSMS_Cliente)
        self.menuReportes.addSeparator()
        self.menuReportes.addAction(self.actionEstatus_Panel)
        self.menuReportes.addAction(self.actionLinea_Receptor)
        self.menuReportes.addAction(self.actionCliente)
        self.menuReportes.addAction(self.actionFicha_Cliente)
        self.menuReportes.addAction(self.actionClientes_sin_Coordenadas)
        self.menuReportes.addAction(self.actionClientes_sin_Imagen)
        self.menuReportes.addAction(self.actionZona_Clientes)
        self.menuReportes.addAction(self.actionClientes_EMpresas)
        self.menuReportes.addAction(self.actionClientes_Ultima_Se_al)
        self.menuReportes.addAction(self.actionClientes_Ultima_A_C)
        self.menuReportes.addAction(self.actionLog_de_Usuarios)
        self.menuMensajeria.addAction(self.actionEnvio_de_SMS)
        self.menuMensajeria.addAction(self.actionEnvio_de_Correos)
        self.menuConfiguracio.addAction(self.actionUsuarios)
        self.menuConfiguracio.addAction(self.actionTipos_de_Usuarios)
        self.menuConfiguracio.addSeparator()
        self.menuConfiguracio.addAction(self.actionEmpresas)
        self.menuConfiguracio.addSeparator()
        self.menuConfiguracio.addAction(self.actionConfiguracion_Vehiculos)
        self.menuConfiguracio.addAction(self.actionParentesco)
        self.menuConfiguracio.addAction(self.actionTipo_de_Cliente)
        self.menuConfiguracio.addAction(self.actionResoluciones)
        self.menuConfiguracio.addAction(self.actionTipo_de_Alarmas)
        self.menuConfiguracio.addAction(self.actionEventos)
        self.menuConfiguracio.addAction(self.actionCodigos_de_Alarma)
        self.menuConfiguracio.addAction(self.actionGrupo_Codigos_de_Alarma)
        self.menuConfiguracio.addAction(self.actionDepartamentos)
        self.menuConfiguracio.addAction(self.actionMotivos_Soporte)
        self.menuConfiguracio.addAction(self.actionReceptores)
        self.menuConfiguracio.addAction(self.actionDias_Feriados)
        self.menuContacto365.addAction(self.actionSolicita_Soporte)
        self.menuContacto365.addAction(self.actionAcerca_de)
        self.menubar.addAction(self.menuMonitoreo.menuAction())
        self.menubar.addAction(self.menuClientes.menuAction())
        self.menubar.addAction(self.menuMapas.menuAction())
        self.menubar.addAction(self.menuVehiculos.menuAction())
        self.menubar.addAction(self.menuReportes.menuAction())
        self.menubar.addAction(self.menuMensajeria.menuAction())
        self.menubar.addAction(self.menuConfiguracio.menuAction())
        self.menubar.addAction(self.menuContacto365.menuAction())
        self.toolBar.addAction(self.actionIngresar_a_Monitoreo)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionLista_de_Clientes)
        self.toolBar.addAction(self.actionNuevo_Cliente)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionGrupos_de_Clientes)
        self.toolBar.addAction(self.actionNuevo_Grupo)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionVer_Mapa)
        self.toolBar.addAction(self.actionZonas)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionEnvio_de_SMS)
        self.toolBar.addAction(self.actionEnvio_de_Correos)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionSolicita_Soporte)

        self.retranslateUi(QMainWindow)
        QtCore.QMetaObject.connectSlotsByName(QMainWindow)

    def retranslateUi(self, QMainWindow):
        QMainWindow.setWindowTitle(_translate("QMainWindow", "365Connect by 365 Monitoring Software. [365monitoreo.com]", None))
        self.menuMonitoreo.setTitle(_translate("QMainWindow", "Monitoreo", None))
        self.menuClientes.setTitle(_translate("QMainWindow", "Clientes", None))
        self.menuMapas.setTitle(_translate("QMainWindow", "Mapas", None))
        self.menuVehiculos.setTitle(_translate("QMainWindow", "Vehiculos", None))
        self.menuReportes.setTitle(_translate("QMainWindow", "Reportes", None))
        self.menuMensajeria.setTitle(_translate("QMainWindow", "SMS/Mail", None))
        self.menuConfiguracio.setTitle(_translate("QMainWindow", "Configuracion", None))
        self.menuContacto365.setTitle(_translate("QMainWindow", "Contacto365", None))
        self.toolBar.setWindowTitle(_translate("QMainWindow", "toolBar", None))
        self.actionLista_de_Clientes.setText(_translate("QMainWindow", "Lista de Clientes", None))
        self.actionLista_de_Clientes.setStatusTip(_translate("QMainWindow", "Listar Todos los Clientes del Sistema", None))
        self.actionLista_de_Clientes.setShortcut(_translate("QMainWindow", "Ctrl+C", None))
        self.actionNuevo_Cliente.setText(_translate("QMainWindow", "Nuevo Cliente", None))
        self.actionNuevo_Cliente.setStatusTip(_translate("QMainWindow", "Agregar un Cliente", None))
        self.actionNuevo_Cliente.setShortcut(_translate("QMainWindow", "Shift+C", None))
        self.actionNuevo_Grupo.setText(_translate("QMainWindow", "Nuevo Grupo", None))
        self.actionNuevo_Grupo.setStatusTip(_translate("QMainWindow", "Crear Nuevo Grupo de Clientes", None))
        self.actionNuevo_Grupo.setShortcut(_translate("QMainWindow", "Shift+G", None))
        self.actionGrupos_de_Clientes.setText(_translate("QMainWindow", "Grupos de Clientes", None))
        self.actionGrupos_de_Clientes.setStatusTip(_translate("QMainWindow", "Listar Grupos de Clientes del Sistema", None))
        self.actionGrupos_de_Clientes.setShortcut(_translate("QMainWindow", "Ctrl+G", None))
        self.actionVer_Mapa.setText(_translate("QMainWindow", "Ver Mapa", None))
        self.actionVer_Mapa.setStatusTip(_translate("QMainWindow", "Ver Mapa de Ubicacion de Clientes", None))
        self.actionVer_Mapa.setShortcut(_translate("QMainWindow", "Ctrl+M", None))
        self.actionZonas.setText(_translate("QMainWindow", "Zonas", None))
        self.actionZonas.setStatusTip(_translate("QMainWindow", "Gestionar Zonas del Mapa", None))
        self.actionZonas.setShortcut(_translate("QMainWindow", "Ctrl+Z", None))
        self.actionActivaciones.setText(_translate("QMainWindow", "Activaciones", None))
        self.actionGrupos_Alarmas.setText(_translate("QMainWindow", "Grupos Alarmas", None))
        self.actionCodigo_ALarmas.setText(_translate("QMainWindow", "Codigo ALarmas", None))
        self.actionEventos_no_definidos.setText(_translate("QMainWindow", "Eventos No Definidos", None))
        self.actionSMS_Totales.setText(_translate("QMainWindow", "SMS Totales", None))
        self.actionSMS_Entrada.setText(_translate("QMainWindow", "SMS Entrada", None))
        self.actionSMS_Cliente.setText(_translate("QMainWindow", "SMS Cliente", None))
        self.actionEstatus_Panel.setText(_translate("QMainWindow", "Estatus Panel", None))
        self.actionLinea_Receptor.setText(_translate("QMainWindow", "Linea Receptor", None))
        self.actionCliente.setText(_translate("QMainWindow", "Cliente", None))
        self.actionFicha_Cliente.setText(_translate("QMainWindow", "Ficha Cliente", None))
        self.actionClientes_sin_Coordenadas.setText(_translate("QMainWindow", "Clientes sin Coordenadas", None))
        self.actionClientes_sin_Imagen.setText(_translate("QMainWindow", "Clientes sin Imagen", None))
        self.actionZona_Clientes.setText(_translate("QMainWindow", "Zona Clientes", None))
        self.actionClientes_EMpresas.setText(_translate("QMainWindow", "Clientes Empresas", None))
        self.actionClientes_Ultima_Se_al.setText(_translate("QMainWindow", "Clientes Ultima Señal", None))
        self.actionClientes_Ultima_A_C.setText(_translate("QMainWindow", "Clientes Ultima A/C", None))
        self.actionLog_de_Usuarios.setText(_translate("QMainWindow", "Log de Usuarios", None))
        self.actionUsuarios.setText(_translate("QMainWindow", "Usuarios", None))
        self.actionTipos_de_Usuarios.setText(_translate("QMainWindow", "Tipos de Usuarios", None))
        self.actionEmpresas.setText(_translate("QMainWindow", "Empresas", None))
        self.actionConfiguracion_Vehiculos.setText(_translate("QMainWindow", "Configuracion Vehiculos", None))
        self.actionParentesco.setText(_translate("QMainWindow", "Parentesco", None))
        self.actionTipo_de_Cliente.setText(_translate("QMainWindow", "Tipo de Cliente", None))
        self.actionResoluciones.setText(_translate("QMainWindow", "Resoluciones", None))
        self.actionTipo_de_Alarmas.setText(_translate("QMainWindow", "Tipo de Alarmas", None))
        self.actionEventos.setText(_translate("QMainWindow", "Eventos", None))
        self.actionCodigos_de_Alarma.setText(_translate("QMainWindow", "Codigos de Alarma", None))
        self.actionGrupo_Codigos_de_Alarma.setText(_translate("QMainWindow", "Grupo Codigos de Alarma", None))
        self.actionDepartamentos.setText(_translate("QMainWindow", "Departamentos", None))
        self.actionMotivos_Soporte.setText(_translate("QMainWindow", "Motivos Soporte", None))
        self.actionReceptores.setText(_translate("QMainWindow", "Receptores", None))
        self.actionDias_Feriados.setText(_translate("QMainWindow", "Dias Feriados", None))
        self.actionSolicita_Soporte.setText(_translate("QMainWindow", "Solicita Soporte", None))
        self.actionSolicita_Soporte.setStatusTip(_translate("QMainWindow", "Obten Soporte Directo con 365", None))
        self.actionSolicita_Soporte.setShortcut(_translate("QMainWindow", "Ctrl+H", None))
        self.actionAcerca_de.setText(_translate("QMainWindow", "Acerca de", None))
        self.actionAcerca_de.setStatusTip(_translate("QMainWindow", "Acerca de 365 Monitoring Software", None))
        self.actionEnvio_de_SMS.setText(_translate("QMainWindow", "Envio de SMS", None))
        self.actionEnvio_de_SMS.setStatusTip(_translate("QMainWindow", "Enviar Mensajes de Texto", None))
        self.actionEnvio_de_SMS.setShortcut(_translate("QMainWindow", "Ctrl+E", None))
        self.actionEnvio_de_Correos.setText(_translate("QMainWindow", "Envio de Correos", None))
        self.actionEnvio_de_Correos.setStatusTip(_translate("QMainWindow", "Enviar Correos Electronicos", None))
        self.actionEnvio_de_Correos.setShortcut(_translate("QMainWindow", "Ctrl+S", None))
        self.actionIngresar_a_Monitoreo.setText(_translate("QMainWindow", "Ingresar a Monitoreo", None))
        self.actionIngresar_a_Monitoreo.setStatusTip(_translate("QMainWindow", "Accede al Area de Monitoreo", None))
        self.actionIngresar_a_Monitoreo.setShortcut(_translate("QMainWindow", "Ctrl+M", None))

import recursos_rc
